---
cops_db_name: db
cops_db_user: user
cops_db_password: secret
cops_mysql__roles:
- name: "{{cops_db_user}}"
  password: "{{cops_db_password}}"
  privs: "{{cops_db_name}}.*"
cops_mysql__databases:
- db: "{{cops_db_name}}"
cops_mysql_name: mysql
mysql_servers: mysql_servers
cops_installer_mode: lazy
# vim:set ft=sls:
